-- AlterTable
ALTER TABLE `Job` ADD COLUMN `currentAccuracy` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `currentEpoch` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `currentLoss` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `loss` DOUBLE NULL,
    ADD COLUMN `progress` INTEGER NOT NULL DEFAULT 0,
    MODIFY `duration` INTEGER NULL;
